### ISSUE TITLE
SkiaCanvas.NativeConcatenateTransform throws exception: The matrix array must have a length of 9

### ISSUE THREAD

**Issue by wieslawsoltes** [dotnet/Microsoft.Maui.Graphics#270]
`The matrix array must have a length of 9. (Parameter 'values')`

https://github.com/dotnet/Microsoft.Maui.Graphics/blob/a6f32d0fa31079997eda0e39e5254c04e8396350/src/Microsoft.Maui.Graphics.Skia/SkiaCanvas.cs#L843

```
   at SkiaSharp.SKMatrix.GetValues(Single[] values)
   at Microsoft.Maui.Graphics.Skia.SkiaCanvas.NativeConcatenateTransform(Matrix3x2 transform)
   at Microsoft.Maui.Graphics.AbstractCanvas`1.ConcatenateTransform(Matrix3x2 transform)
   at Microsoft.Maui.Graphics.ScalingCanvas.ConcatenateTransform(Matrix3x2 transform)
   at Microsoft.Maui.Graphics.PictureCanvas.<>c__DisplayClass64_0.<ConcatenateTransform>b__0(ICanvas canvas)
   at Microsoft.Maui.Graphics.StandardPicture.Draw(ICanvas canvas)
```

version 6.0.101-preview.11.758

**Comment by gregblastue4** [comment]
Hello, I just stumbled upon this bug while trying to rebuild a MAUI application with SkiaSharp and this library. Since there is no plan to fix this, what is the intended workaround for it?
